apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-uniform-cluster-ini-cm
  namespace: cp4i
data:
  config.ini: |-
    AutoCluster:
      Repository2Conname=uniform-cluster-qm1-ibm-mq.cp4i.svc(1414)
      Repository2Name=QM1
      Repository1Conname=uniform-cluster-qm2-ibm-mq.cp4i.svc(1414)
      Repository1Name=QM2
      ClusterName=DEMOCLUSTER
      Type=Uniform
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-uniform-cluster-mqsc-cm
  namespace: cp4i
data:
  common_config.mqsc: |-
    define channel('+AUTOCL+_+QMNAME+') chltype(clusrcvr) trptype(tcp) conname(+CONNAME+) cluster('+AUTOCL+') replace
    define QL(APPQ1) cluster(DEMOCLUSTER) defbind(notfixed) clwluseq(any) maxdepth(99999999) replace
    define QL(APPQ2) cluster(DEMOCLUSTER) defbind(notfixed) clwluseq(any) maxdepth(99999999) replace
    define channel(DEF.SVRCONN) chltype(SVRCONN) trptype(TCP) sslcauth(OPTIONAL) sslciph('ANY_TLS12_OR_HIGHER') replace
    set chlauth(DEF.SVRCONN) type(BLOCKUSER) userlist('nobody') action(ADD)
    DEFINE CHANNEL('IBM.APP.SVRCONN') CHLTYPE(SVRCONN) TRPTYPE(TCP) sslcauth(OPTIONAL) sslciph('ANY_TLS12_OR_HIGHER') REPLACE
    ALTER QMGR CHLAUTH (DISABLED)
    REFRESH SECURITY TYPE(CONNAUTH)
    DEFINE QLOCAL(TEST.DYNAMIC.QUEUE.1)   
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mq-uniform-cluster-qm1-mqsc-cm
  namespace: cp4i
data:
  qm1-config.mqsc: |-
    alter chl(DEMOCLUSTER_QM1) chltype(CLUSRCVR) conname('uniform-cluster-qm1-ibm-mq.cp4i.svc(1414)')
    alter chl(DEMOCLUSTER_QM2) chltype(CLUSSDR) conname('uniform-cluster-qm2-ibm-mq.cp4i.svc(1414)')
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-uniform-cluster-qm2-mqsc-cm
  namespace: cp4i
data:
  qm2-config.mqsc: |-
    alter chl(DEMOCLUSTER_QM1) chltype(CLUSSDR) conname('uniform-cluster-qm1-ibm-mq.cp4i.svc(1414)')
    alter chl(DEMOCLUSTER_QM2) chltype(CLUSRCVR) conname('uniform-cluster-qm2-ibm-mq.cp4i.svc(1414)')
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-uniform-cluster-qm3-mqsc-cm
  namespace: cp4i
data:
  qm3-config.mqsc: |-
    alter chl(DEMOCLUSTER_QM1) chltype(CLUSSDR) conname('uniform-cluster-qm1-ibm-mq.cp4i.svc(1414)')
    alter chl(DEMOCLUSTER_QM2) chltype(CLUSRCVR) conname('uniform-cluster-qm2-ibm-mq.cp4i.svc(1414)')