apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cloud-native-postgresql-4.22.0+20240307.065137.1505
  publisher: IBM
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:3a44f3e7f01e4eb72d192008f1502777dc10751b68e40da2e1d38d23f2907ce7
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s